/* eslint-disable prettier/prettier */
const AUTH_ACTION_TYPES = {
    LOGIN_REQUEST: 'LOGIN_REQUEST',
    LOGIN_FAILURE: 'LOGIN_FAILURE',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',

    BUYER_LIST_REQUEST: 'BUYER_LIST_REQUEST',
    BUYER_LIST_FAILURE: 'BUYER_LIST_FAILURE',
    BUYER_LIST_SUCCESS: 'BUYER_LIST_SUCCESS',

    LOGIN_CLEANUP_FAILURE: 'LOGIN_CLEANUP_FAILURE',

    SET_USER_LANGUAGE: 'SET_USER_LANGUAGE',
    USER_LOGGED_OUT: 'USER_LOGGED_OUT',
    SET_ACCOUNT_ID: 'SET_ACCOUNT_ID',
    RESET_PRODUCT_LIST_PAGINATION_INFO: 'RESET_PRODUCT_LIST_PAGINATION_INFO'
};
export default AUTH_ACTION_TYPES;
