/* eslint-disable prettier/prettier */
export const de = {
  navigator: {
    home: 'Produkte',
    cart: 'Warenkorb',
  },
  common: {
    productCatalogue: 'Produkte',
    filter: 'Filtern',
    productDetail: 'Produktdetail',
    buyingList: 'Einkaufsliste',
    products: 'Produkte',
    seasonal: 'saisonal',
    searchProduct: 'Produkt suchen',
    categories: 'Kategorien',
    cart: 'Einkaufswagen',
    deliverSeparetely: 'Separat liefern',
    orderDate: 'Bestelldatum',
    totalPrice: 'Gesamtpreis',
    subTotal: 'Zwischensumme',
    price: 'Preis',
    addComment: 'Einen Kommentar hinzufügen',
    productCurrentDayRule: 'Regel für den aktuellen Tag des Produkts',
    aboutThisProduct: 'Informationen zu diesem Produkt',
    aboutProduct: 'Über das Produkt',
    features: 'Merkmale',
    productSpecifications: 'Produktspezifikation',
    artcileNo: 'Artikel Nummer',
    origin: 'Herkunft',
    brand: 'Marke',
    packagingInfo: 'Verpackungsinfo',
    relatedProducts: 'Verwandte Produkte',
    password: 'Passwort *',
    emailUserName: 'Benutzername oder E-mail Adresse *',
    notLogin: 'Sie haben sich nicht angemeldet, bitte melden Sie sich an',
    noInternet: 'Sie sind nicht mit dem Internet verbunden',
    delete: 'Sind Sie sicher, dass Sie löschen möchten ?',
    noData: 'Keine Daten',
    orderHistory: 'Bestellverlauf',
    thankyoufororder: 'Danke für Ihren Einkauf',
    clickonme: 'Klicken Sie auf die Schaltfläche, um Ihre Bestellhistorie anzuzeigen',
    login: 'Einloggen',
    orderNumber: 'Bestellnummer',
    orderedOn: 'Bestellt am',
    deliverOn: 'Geliefert am',
    total: 'Gesamt',
    for: 'zum',
    items: 'Artikel',
    selectQuantity: 'Bitte Menge auswählen',
    selectBuyingList: 'Wählen Sie Einkaufsliste',
  },
  menu: {
    orderDetails: 'Bestelldetails',
    orderHistory: 'Bestellverlauf',
    myAccount: 'Mein Konto',
    contactUs: 'Kontaktiere uns',
    faqs: 'Häufig gestellte Fragen',
    helpSupport: 'Hilfe Unterstützung',
    impressum: 'Impressum',
    signOut: 'Ausloggen',
  },
  createList: {
    createList: 'Erstelle Liste',
    enterListName: 'Geben Sie den Listennamen ein',
  },
  actions: {
    addList: 'Liste hinzufügen',
    addCart: 'in den Warenkorb legen',
    clearAll: 'Alles löschen',
    done: 'Fertig',
    checkout: 'Eine Bestellung Aufgeben',
    login: 'Anmeldung',
    yes: 'Jawohl',
    no: 'Nein',
    view: 'Aussicht',
    reOrder: 'Nachbestellen',
  },
};
