/* eslint-disable prettier/prettier */
export const NAVIGATION = {
  homeNew: "homeNew",
  homeNewChild: "homeNewChild",
  homeFilter: "homeFilter",
  buyingProductList: 'BuyingProductList',
  buyingList: 'BuyingList',
  addList: 'AddList',
  productListing: 'ProductListing',
  filter: 'Filter',
  categoryFilter: 'CategoryFilter',
  productList: 'ProductList',
  categoryList: 'CategoryList',
  categoriesProductList: 'CategoriesProductList',
  cart: 'Cart',
  login: 'Login',
  selectUser: 'SelectUser',
  myOrder: 'MyOrder',
  contact: 'Contact',
  faqs: 'Faqs',
  myAccount: 'MyAccount',
  support: 'Support',
  impressum: 'Impressum',
  productDetail: 'ProductDetail',
  orderDetails: 'OrderDetails',
  orderHistory: 'Order History',
  productLists: 'ProductLists',
  searchlist: 'SearchList',
  productfilter: 'ProductFilter'
};
